### ISSUE TITLE
Running last test

### ISSUE THREAD

**Issue by stevanmilic** [rcarriga/neotest#4]
Is it possible to implement a feature to run last test execution, similar to what exists for vim-test?

**Comment by rcarriga** [comment]
Added in latest commit, see `:h neotest.run.run_last` :smile:

**Comment by stevanmilic** [comment]
thank you!

**Comment by pernambucano** [comment]
I know this is closed but just wanted to thank you for this, it will help my TDD process a lot  (as I usually am seeing the code instead of the test after it went into the green state).
